StartupEvents.registry('block', event => {
  event.create('gravity_tune_casing')
    .displayName('重力調律ケーシング')
    .hardness(5.0)
    .resistance(10.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .fullBlock(true)
    .textureAll('kubejs:block/gravity_tune_casing')
})
