
GTCEuStartupEvents.registry('gtceu:material', event => {
event.create('ameijia_air')
    .fluid()
    .color(0xB3472E)
    .iconSet(GTMaterialIconSet.DULL)
    .formula('(Co2)110(N2)50Ar16(??)11(SO2)10Eg3')
    event.create('liquit_ameizia_air')
    .fluid()
    .color(0xBB472E)
    .iconSet(GTMaterialIconSet.DULL)
    .formula('(Co2)110(N2)50Ar16(??)11(SO2)10Eg3')
    event.create('ameizia_stagnation')
    
    .liquid(0)
    .color(0xFFE2DA)
    .iconSet(GTMaterialIconSet.DULL)
    .formula('??')
        event.create('low_constains_enigma')
    .fluid()
    .color(0x7A3F8F)
    .iconSet(GTMaterialIconSet.DULL)
    .formula('Fe16Nr6Eg3St2Ar3')
        event.create('high_constains_enigma')
    .fluid()
    .color(0x8C45A6)
    .iconSet(GTMaterialIconSet.DULL)
    .formula('Nr11Eg9St3Ar4Fe3')
})