// kubejs/startup_scripts/gt_multiblocks.js

GTCEuStartupEvents.registry('gtceu:machine', event => {
    
    // precision_centrifuge
    event.create('precision_centrifuge', 'multiblock')
        .recipeModifier(GTRecipeModifiers.OC_PERFECT)
        .rotationState(RotationState.NON_Y_AXIS)
        .appearanceBlock(() => Block.getBlock('gtceu:vibration_safe_casing'))
        .recipeTypes(['centrifuge','thermal_centrifuge','precision_centrifuge']) 
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("XXXXXAAAXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXAAAXXXXX")
            .aisle("XXXAABBBAAXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXAABBBAAXXX")
            .aisle("XXABBBBBBBAXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXABBBBBBBAXX")
            .aisle("XABBBBBBBBBAX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XABBBBBBBBBAX")
            .aisle("XABBBBBBBBBAX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XABBBBBBBBBAX")
            .aisle("ABBBBBBBBBBBA", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "ABBBBBBBBBBBA")
            .aisle("ABBBBBBBBBBBA", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "ABBBBBBBBBBBA")
            .aisle("ABBBBBBBBBBBA", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "CXXXXXXXXXXXC", "ABBBBBBBBBBBA")
            .aisle("XABBBBBBBBBBA", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XABBBBBBBBBBA")
            .aisle("XABBBBBBBBBAX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XCXXXXXXXXXCX", "XABBBBBBBBBAX")
            .aisle("XXABBBBBBBAXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXCXXXXXXXCXX", "XXABBBBBBBAXX")
            .aisle("XXXAABBBAAXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXCCXXXCCXXX", "XXXAABBBAAXXX")
            .aisle("XXXXXAZAXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXCCCXXXXX", "XXXXXAAAXXXXX")

            .where('Z', Predicates.controller(Predicates.blocks(definition.get())))
            .where('X', Predicates.any())
            .where('A', Predicates.blocks('gtceu:atomic_casing')
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1).setMaxGlobalLimited(2))
            )
            .where('B', Predicates.blocks('gtceu:sturdy_machine_casing'))
            .where('C', Predicates.blocks('gtceu:vibration_safe_casing').setMinGlobalLimited(380)
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16))   // レシピタイプいっぱいなので機能ブロックもいっぱい
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16))   
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(12))   
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(12))  
            )
            
            .build()
        )
        .workableCasingRenderer(
            "gtceu:block/casings/gcym/vibration_safe_casing", 
            "gtceu:block/machines/centrifuge", 
            false
        )
})