GTCEuStartupEvents.registry('gtceu:machine', event => {
  event.create('gravity_well', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeType('gravity_well')
    .recipeModifier(GTRecipeModifiers.OC_PERFECT)
    .appearanceBlock(() => Block.getBlock('gtceu:uhv_machine_casing'))
    .pattern(definition => FactoryBlockPattern.start()

      .aisle("XXXAAAAAXXX", "XXAAAAAAAXX", "XAAAAAAAAAX", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "XAAAAAAAAAX", "XXAAAAAAAXX", "XXXAAAAAXXX")
      .aisle("XXABBBBBAXX", "XAXXXXXXXAX", "AXXXXXXXXXA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "XAXXXXXXXAX", "XAXXXXXXXAX", "XXAXXXXXAXX")
      .aisle("XABBBBBBBAX", "AXXXXXXXXXA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "AXXXXXXXXXA", "XABBBBBBBAX")
      .aisle("ABBBBBBBBBA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXCCCXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "ABBBBBBBBBA")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXCCCXXXB", "BXXCCECCXXB", "BXXXCCCXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXCXXXXXCXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXFXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXFXXXXB", "BXXXFXFXXXB", "BXXXXFXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXFXXXXB", "BXXXFXFXXXB", "BXXFXEXFXXB", "BXXXFXFXXXB", "BXXXXFXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXFXXXXB", "BXXXFXFXXXB", "BXXXXFXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXFXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXCXXXXXCXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("DBBBBBBBBBD", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXCCCXXXB", "BXXCCECCXXB", "BXXXCCCXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "DBBBBBBBBBD")
      .aisle("ABBBBBBBBBA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXCCCXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "ABBBBBBBBBA")
      .aisle("XABBBBBBBAX", "AXXXXXXXXXA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXCXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "AXXXXXXXXXA", "XABBBBBBBAX")
      .aisle("XXABBBBBAXX", "XAXXXXXXXAX", "AXXXXXXXXXA", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "BXXXXXXXXXB", "AXXXXXXXXXA", "XAXXXXXXXAX", "XXABBBBBAXX")
      .aisle("XXXAAAAAXXX", "XXAAAAAAAXX", "XAAAAAAAAAX", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAYAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "XAAAAAAAAAX", "XXAAAAAAAXX", "XXXAAAAAXXX")

      .where('Y', Predicates.controller(Predicates.blocks(definition.getBlock())))

     .where('A', Predicates.blocks('gtceu:uhv_machine_casing')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)).or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1).setExactLimit(2)))
            .where('B', Predicates.blocks('gtceu:tempered_glass'))
            .where('C', Predicates.blocks('gtceu:atomic_casing'))
            .where('D', Predicates.blocks('gtceu:neutronium_frame'))
            .where('E', Predicates.blocks('kubejs:glavity_defrection_block')) 
            .where('F', Predicates.blocks('gtceu:ruthenium_trinium_americium_neutronate_block'))
            .where('X', Predicates.air())
            .build())
    
    .workableCasingRenderer(
      "gtceu:block/casings/voltage/uhv/side",
      "gtceu:block/multiblock/implosion_compressor",
      false
    )
})
